server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://causeteam15:causeteam15@cluster0.q4th0s9.mongodb.net/datadb
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs